name: WispBlockBreak
version: ${project.version}
main: dev.yhdiamond.wispblockbreak.WispBlockBreak
api-version: 1.16
commands:
  wispblockbreak:
    description: Start the wisp block break challenge
    usage: /wispblockbreak <start/stop/reload>
